routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => 'web'], function(){



});

Route::group(['middleware' => ['web', 'cekuser:1' ]], function(){
   Route::get('divisi/data', 'DivisiController@listData')->name('divisi.data');
   Route::resource('divisi', 'DivisiController');

   Route::get('santri/data', 'SantriController@listData')->name('santri.data');
   Route::post('santri/hapus', 'SantriController@deleteSelected');
   Route::post('santri/cetak', 'SantriController@printBarcode');
   Route::get('santri/{id}/lihat', 'SantriController@show');   
   Route::resource('santri', 'SantriController');

});

app/Divisi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Divisi extends Model
{
    protected $table = 'divisi';
	protected $primaryKey = 'id_divisi';
	
	public function santri(){
		return $this->hasMany('App\Santri', 'id_divisi');
	}
}

app/Http/Controllers/DivisiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Divisi;

class DivisiController extends Controller
{
   public function index()
   {
      return view('divisi.index'); 
   }

   public function listData()
   {
   
     $divisi = Divisi::orderBy('id_divisi', 'desc')->get();
     $no = 0;
     $data = array();
     foreach($divisi as $list){
       $no ++;
       $row = array();
       $row[] = $no;
       $row[] = $list->nama_divisi;
       $row[] = '<div class="btn-group">
               <a onclick="editForm('.$list->id_divisi.')" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
               <a onclick="deleteData('.$list->id_divisi.')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a></div>';
       $data[] = $row;
     }

     $output = array("data" => $data);
     return response()->json($output);
   }

   public function store(Request $request)
   {
      $divisi = new Divisi;
      $divisi->nama_divisi = $request['nama'];
      $divisi->save();
   }

   public function edit($id)
   {
     $divisi = Divisi::find($id);
     echo json_encode($divisi);
   }

   public function update(Request $request, $id)
   {
      $divisi = Divisi::find($id);
      $divisi->nama_divisi = $request['nama'];
      $divisi->update();
   }

   public function destroy($id)
   {
      $divisi = Divisi::find($id);
      $divisi->delete();
   }
}

resources/views/divisi/form.blade.php
<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
     
   <form class="form-horizontal" data-toggle="validator" method="post">
   {{ csrf_field() }} {{ method_field('POST') }}
   
   <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times; </span> </button>
      <h3 class="modal-title"></h3>
   </div>
            
<div class="modal-body">
   
   <input type="hidden" id="id" name="id">
   <div class="form-group">
      <label for="nama" class="col-md-3 control-label">Nama Divisi</label>
      <div class="col-md-6">
         <input id="nama" type="text" class="form-control" name="nama" autofocus required>
         <span class="help-block with-errors"></span>
      </div>
   </div>
   
</div>
   
   <div class="modal-footer">
      <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
      <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-arrow-circle-left"></i> Batal</button>
   </div>
      
   </form>

         </div>
      </div>
   </div>

resources/views/divisi/index.blade.php
@extends('layouts.app')

@section('title')
  Daftar Divisi Di Pondok IT
@endsection

@section('breadcrumb')
   @parent
   <li>divisi</li>
@endsection

@section('content')     
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <a onclick="addForm()" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
      </div>
      <div class="box-body">  

<table class="table table-striped">
<thead>
   <tr>
      <th width="30">No</th>
      <th>Nama Kategori</th>
      <th width="100">Aksi</th>
   </tr>
</thead>
<tbody></tbody>
</table>

      </div>
    </div>
  </div>
</div>

@include('divisi.form')
@endsection

@section('script')
<script type="text/javascript">
var table, save_method;
$(function(){
   table = $('.table').DataTable({
     "processing" : true,
     "ajax" : {
       "url" : "{{ route('divisi.data') }}",
       "type" : "GET"
     }
   }); 
   
   $('#modal-form form').validator().on('submit', function(e){
      if(!e.isDefaultPrevented()){
         var id = $('#id').val();
         if(save_method == "add") url = "{{ route('divisi.store') }}";
         else url = "divisi/"+id;
         
         $.ajax({
           url : url,
           type : "POST",
           data : $('#modal-form form').serialize(),
           success : function(data){
             $('#modal-form').modal('hide');
             table.ajax.reload();
           },
           error : function(){
             alert("Tidak dapat menyimpan data!");
           }   
         });
         return false;
     }
   });
});

function addForm(){
   save_method = "add";
   $('input[name=_method]').val('POST');
   $('#modal-form').modal('show');
   $('#modal-form form')[0].reset();            
   $('.modal-title').text('Tambah Divisi');
}

function editForm(id){
   save_method = "edit";
   $('input[name=_method]').val('PATCH');
   $('#modal-form form')[0].reset();
   $.ajax({
     url : "divisi/"+id+"/edit",
     type : "GET",
     dataType : "JSON",
     success : function(data){
       $('#modal-form').modal('show');
       $('.modal-title').text('Edit Divisi');
       
       $('#id').val(data.id_divisi);
       $('#nama').val(data.nama_divisi);
       
     },
     error : function(){
       alert("Tidak dapat menampilkan data!");
     }
   });
}

function deleteData(id){
   if(confirm("Apakah yakin data akan dihapus?")){
     $.ajax({
       url : "divisi/"+id,
       type : "POST",
       data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
       success : function(data){
         table.ajax.reload();
       },
       error : function(){
         alert("Tidak dapat menghapus data!");
       }
     });
   }
}
</script>
@endsection