routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => 'web'], function(){



});

Route::group(['middleware' => ['web', 'cekuser:1' ]], function(){
   Route::get('divisi/data', 'DivisiController@listData')->name('divisi.data');
   Route::resource('divisi', 'DivisiController');

   Route::get('santri/data', 'SantriController@listData')->name('santri.data');
   Route::post('santri/hapus', 'SantriController@deleteSelected');
   Route::post('santri/cetak', 'SantriController@printBarcode');
   Route::get('santri/{id}/lihat', 'SantriController@show');   
   Route::resource('santri', 'SantriController');

});

app/Santri.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Santri extends Model
{
   protected $table = 'santri';
   protected $primaryKey = 'id_santri';
   
   public function divisi(){
      return $this->belongsTo('App\Divisi');
   }
}

app/Http/Controllers/SantriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Santri;
use App\Divisi;
use DataTables;
use PDF;

class SantriController extends Controller
{
    public function index()
    {
       $divisi = Divisi::all();      
       return view('santri.index', compact('divisi'));
    }

    public function listData()
    {
    
      $santri = Santri::leftJoin('divisi', 'divisi.id_divisi', '=', 'santri.id_divisi')
      ->orderBy('santri.id_santri', 'desc')
      ->get();
        $no = 0;
        $data = array();
        foreach($santri as $list){
          $no ++;
          $row = array();
           $row[] = "<input type='checkbox' name='id[]'' value='".$list->id_santri."'>";
          $row[] = $no;
          $row[] = $list->nama_santri;
          $row[] = $list->nama_divisi;
          $row[] = $list->alamat;
          $row[] = $list->phone;

          $row[] = "
            <div class='btn-group'>
                <a onclick='editForm(".$list->id_santri.")' class='btn btn-primary btn-sm'><i class='fa fa-pencil'></i></a>
                <a onclick='deleteData(".$list->id_santri.")' class='btn btn-danger btn-sm'><i class='fa fa-trash'></i></a>
            </div>";
          $data[] = $row;
        }
        
        return Datatables::of($data)->escapeColumns([])->make(true);
    }

    public function store(Request $request)
    {

            $santri = new Santri;
            $santri->nama_santri    = $request['nama'];
            $santri->id_divisi      = $request['divisi'];
            $santri->alamat      = $request['alamat'];
            $santri->phone     = $request['phone'];
            $santri->save();
    }

    public function edit($id)
    {
      $santri = Santri::find($id);
      echo json_encode($santri);
    }

    public function update(Request $request, $id)
    {
        $santri = Santri::find($id);
        $santri = new Santri;
        $santri->nama_santri    = $request['nama'];
        $santri->id_divisi      = $request['divisi'];
        $santri->alamat      = $request['alamat'];
        $santri->phone     = $request['phone'];
        $santri->update();
        echo json_encode(array('msg'=>'success'));
    }

    public function destroy($id)
    {
        $santri = Santri::find($id);
        $santri->delete();
    }

    public function deleteSelected(Request $request)
    {
        foreach($request['id'] as $id){
            $santri = Santri::find($id);
            $santri->delete();
        }
    }

}

resources/views/santri/form.blade.php
<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
    
   <form class="form-horizontal" data-toggle="validator" method="post" enctype="multipart/form-data">
   {{ csrf_field() }} {{ method_field('POST') }}
   
   <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times; </span> </button>
      <h3 class="modal-title"></h3>
   </div>

<div class="modal-body">
<input type="hidden" id="id" name="id"> 

  <div class="form-group">
    <label for="nama" class="col-md-3 control-label">Nama Santri</label>
    <div class="col-md-6">
      <input id="nama" type="text" class="form-control" name="nama" required>
      <span class="help-block with-errors"></span>
    </div>
  </div>

  <div class="form-group">
    <label for="divisi" class="col-md-3 control-label">Kategori</label>
    <div class="col-md-6">
      <select id="divisi" type="text" class="form-control" name="divisi" required>
        <option value=""> -- Pilih Divisi-- </option>
        @foreach($divisi as $list)
        <option value="{{ $list->id_divisi }}">{{ $list->nama_divisi }}</option>
        @endforeach
      </select>
      <span class="help-block with-errors"></span>
    </div>
  </div>

  <div class="form-group">
    <label for="alamat" class="col-md-3 control-label">Alamat</label>
    <div class="col-md-6">
      <input id="alamat" type="text" class="form-control" name="alamat" required>
      <span class="help-block with-errors"></span>
    </div>
  </div>

  <div class="form-group">
    <label for="phone" class="col-md-3 control-label">No Telepon</label>
    <div class="col-md-3">
      <input id="phone" type="text" class="form-control" name="phone" required>
      <span class="help-block with-errors"></span>
    </div>
  </div>

</div>
   
   <div class="modal-footer">
      <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
      <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-arrow-circle-left"></i> Batal</button>
   </div>
    
   </form>

         </div>
      </div>
   </div>

resources/views/santri/index.blade.php
@extends('layouts.app')

@section('title')
  Daftar Santri Pondok IT
@endsection

@section('breadcrumb')
   @parent
   <li>santri</li>
@endsection

@section('content')     
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <a onclick="addForm()" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
        <a onclick="deleteAll()" class="btn btn-danger"><i class="fa fa-trash"></i> Hapus Masal</a>
      </div>
      <div class="box-body">  

<form method="post" id="form-produk">
{{ csrf_field() }}
<table class="table table-striped">
<thead>
   <tr>
      <th width="20"><input type="checkbox" value="1" id="select-all"></th>
      <th width="20">No</th>
      <th>Nama</th>
      <th>Divisi</th>
      <th>Alamat</th>
      <th>Telepon </th>
      <th width="100">Aksi</th>
   </tr>
</thead>
<tbody></tbody>
</table>
</form>

      </div>
    </div>
  </div>
</div>

@include('santri.form')

@endsection

@section('script')
<script type="text/javascript">
var table, save_method, table1;
$(function(){
   table = $('.table').DataTable({
     "processing" : true,
     "serverside" : true,
     "ajax" : {
       "url" : "{{ route('santri.data') }}",
       "type" : "GET"
     },
     'columnDefs': [{
         'targets': 0,
         'searchable': false,
         'orderable': false
      }],
      'order': [1, 'asc']
   }); 

   
   $('#select-all').click(function(){
      $('input[type="checkbox"]').prop('checked', this.checked);
   });

   $('#modal-form form').validator().on('submit', function(e){
      if(!e.isDefaultPrevented()){
         var id = $('#id').val();
         if(save_method == "add") url = "{{ route('santri.store') }}";
         else url = "santri/"+id;
         
         $.ajax({
           url : url,
           type : "POST",
           data : $('#modal-form form').serialize(),
           success : function(data){
             $('#modal-form').modal('hide');
             table.ajax.reload();
           },
           error : function(){
             alert("Tidak dapat menyimpan data!");
           }   
         });
         return false;
     }
   });
});

function addForm(){
   save_method = "add";
   $('input[name=_method]').val('POST');
   $('#modal-form').modal('show');
   $('#modal-form form')[0].reset();            
   $('.modal-title').text('Tambah Santri');
   $('#kode').attr('readonly', false);
}

function editForm(id){
   save_method = "edit";
   $('input[name=_method]').val('PATCH');
   $('#modal-form form')[0].reset();
   $.ajax({
     url : "santri/"+id+"/edit",
     type : "GET",
     dataType : "JSON",
     success : function(data){
       $('#modal-form').modal('show');
       $('.modal-title').text('Edit Santri');
       
       $('#id').val(data.id_santri);
       $('#nama').val(data.nama_santri);
       $('#divisi').val(data.id_divisi);
       $('#alamat').val(data.alamat);
       $('#phone').val(data.phone);
       
     },
     error : function(){
       alert("Tidak dapat menampilkan data!");
     }
   });
}

function deleteData(id){
  if(confirm("Apakah yakin data akan dihapus?")){
     $.ajax({
       url : "santri/"+id,
       type : "POST",
       data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
       success : function(data){
         table.ajax.reload();
       },
       error : function(){
         alert("Tidak dapat menghapus data!");
       }
     });
   }
}

function deleteAll(){
  if($('input:checked').length < 1){
    alert('Pilih data yang akan dihapus!');
  }else if(confirm("Apakah yakin akan menghapus semua data terpilih?")){
     $.ajax({
       url : "santri/hapus",
       type : "POST",
       data : $('#form-produk').serialize(),
       success : function(data){
         table.ajax.reload();
       },
       error : function(){
         alert("Tidak dapat menghapus data!");
       }
     });
   }
}

</script>
@endsection